#!/bin/bash

# AUTHOR: Hunter Hammond
# VERSION: 1.7
# Wrapper for bing.py and wolfram.py

KWARGS="$@"
BROWSER="iceweasel"
DIR=$(cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)
BING=$(python $DIR/bing.py $KWARGS)
if echo $BING | grep -q "BingOpenUrl" ; then
    BING=${BING%$'BingOpenUrl'}
    $BROWSER $BING &
elif echo $BING | grep -q "BingFirstVal" ; then
    BING=${BING%$'BingFirstVal'}
    $BROWSER $BING &
elif echo $BING | grep -q "BingReturnVal" ; then
    BING=${BING%$'BingReturnVal'}
    if [[ $BING = 'q' ]] ; then
        exit 0
    else
        $BROWSER $BING &
    fi
elif echo $BING | grep -q "CalcReturnVal" ; then
    BING=${BING%$'CalcReturnVal'}
    echo $BING
else
    WOLF=$(python $DIR/wolfram.py $KWARGS)
    if echo $WOLF | grep -q "WolfNoMatch" ; then
        KWARGS="-s "$KWARGS
        BING=$(python $DIR/bing.py $KWARGS)
        if echo $BING | grep -q "BingReturnVal" ; then
            BING=${BING%$'BingReturnVal'}
            if [[ $BING = 'q' ]] ; then
                exit 0
            else
                $BROWSER $BING &
            fi
        fi
    else
        echo $WOLF
    fi
fi
